spring:
  ai:
    openai:
      api-key: ${ARK_API_KEY}
      base-url: https://ark.cn-beijing.volces.com/api/v3
      chat:
        options:
          model: doubao-seed-1-6-lite-251015
    mcp:
      clients:
        napcat:
          transport: stdio
          command:
            - java
            - -jar
            - ../simbot-mcp-server-napcat/target/simbot-mcp-server-napcat.jar
