simbot:
  # simbot.application: 与 Application 相关的配置
  application:
    application-launch-mode: none
  # simbot.bots: 与 bot 配置相关的属性。
  bots:
    auto-registration-failure-policy: ERROR
    auto-registration-mismatch-configurable-bot-manager-policy: ERROR_LOG
    auto-registration-resource-load-failure-policy: ERROR
    auto-start-bots: true
    auto-start-mode: ASYNC
    configuration-json-resources:
      - 'classpath:simbot-bots/*.bot.json'
  # simbot.components: 组件相关的配置信息。
  components:
    auto-install-providers: true
    auto-install-provider-configures: true

  # simbot.plugins: 插件相关的配置信息。
  plugins:
    auto-install-providers: true
    auto-install-provider-configures: true

# application.yml
spring:
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8

# 火山方舟（豆包API）配置
volc:
  ark:
    api-key: ${ARK_API_KEY}
    base-url: https://ark.cn-beijing.volces.com/api/v3
    model: kimi-k2-thinking-251104
    models:
      - deepseek-v3-2-251201
      - doubao-seed-1-6-251015
      - doubao-seedance-1-0-pro-250528
      - doubao-seed-1-6-vision-250815
      - doubao-seed-1-6-thinking-250715
      - doubao-seed-1-6-flash-250828
      - doubao-seed-1-6-lite-251015
      - doubao-seed-code-preview-251028
      - doubao-1-5-thinking-pro-250415
      - deepseek-v3-1-terminus
      - doubao-1.5-vision-pro-250328
      - doubao-1-5-ui-tars-250428
      - deepseek-r1-250528
      - deepseek-v3-250324
      - doubao-1-5-pro-32k-250115
      - doubao-1-5-pro-256k-250115
      - doubao-1-5-lite-32k-250115
      - kimi-k2-thinking-251104