spring:
  profiles:
    active: robot
  datasource:
    url: jdbc:mariadb://localhost:3306/simbot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: simbot_user
    password: simbot_pass
