spring:
  profiles:
    active: robot
  datasource:
    url: jdbc:mariadb://localhost:3306/user_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: jasper_user
    password: jasper_pass