spring:
  ai:
    openai:
      # 你的火山方舟 API Key（sk-开头）
      api-key: ${ARK_API_KEY}
      # 火山方舟 OpenAI 兼容接口地址（固定）
      base-url: https://ark.cn-beijing.volces.com/api/v3
      # 火山方舟模型配置（控制台复制的模型名）
      chat:
        options:
          model: doubao-seed-1-6-flash-250828
          max-tokens: 8192
          temperature: 0.7
    ark:
      api:
        chat-api: /chat/completions
        responses-api: /responses
      models:
        - doubao-seed-1-6-flash-250828
        - deepseek-v3-2-251201
        - doubao-seed-code-preview-251028
        - doubao-seed-1-6-lite-251015
        - doubao-seed-translation-250915
        - doubao-seed-1-6-vision-250815
        - deepseek-v3-1-terminus
        - kimi-k2-thinking-251104